import 'package:hive/hive.dart';
import 'recipe_adapter.dart'; // Assuming your Recipe model is defined here

part 'meal_plan.g.dart'; // This will be generated by Hive

@HiveType(typeId: 1)
class MealPlan {
  @HiveField(0)
  final Map<int, Recipe> weeklyMealPlan;

  MealPlan({required this.weeklyMealPlan});
}
